### PR TITLE
Updated FEniCS demo code

### PR DESCRIPTION
**Pull request by Jagirhussan**
Updated the code base with pull request 109
https://github.com/reaktoro/reaktoro/pull/109

and added FEniCS transport demo code hosted at https://bitbucket.org/reaktoro/reaktoro/src/master/unsupported/reaktoro-fenics/

with changes to accommodate signature changes enacted in FEniCS 2019.1.0 release.

### CODE REVIEW

**Comment by allanleal** [comment]
@Jagirhussan Thanks for initiating this! Did you manage to fix these codes to current API of both Reaktoro and FEniCS?

**Comment by Jagirhussan** [comment]
Hi Allan,    Yes, the uploaded code was updated to use the current API of reaktoro and FEniCS release 2019. The demo runs and produces an output file that can be viewed using paraview. However, no check regarding the validity of the results were made.Thanks Jagir 
-------- Original message --------From: Allan Leal <notifications@github.com> Date: 3/09/19  17:20  (GMT+12:00) To: reaktoro/reaktoro <reaktoro@noreply.github.com> Cc: Jagir Hussan <r.jagir@auckland.ac.nz>, Mention <mention@noreply.github.com> Subject: Re: [reaktoro/reaktoro] Updated FEniCS demo code (#111) 
@Jagirhussan Thanks for initiating
 this! Did you manage to fix these codes to current API of both Reaktoro and FEniCS?
—
You are receiving this because you were mentioned.
Reply to this email directly, 
view it on GitHub, or 
mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/reaktoro/reaktoro/pull/111?email_source=notifications\u0026email_token=AA4YXQBKTPVZBQXI7WQWNJTQHXX2XA5CNFSM4ITAWEXKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD5XBK3I#issuecomment-527308141",
"url": "https://github.com/reaktoro/reaktoro/pull/111?email_source=notifications\u0026email_token=AA4YXQBKTPVZBQXI7WQWNJTQHXX2XA5CNFSM4ITAWEXKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD5XBK3I#issuecomment-527308141",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Warmblood-b** [comment]
> Hi Allan,    Yes, the uploaded code was updated to use the current API of reaktoro and FEniCS release 2019. The demo runs and produces an output file that can be viewed using paraview. However, no check regarding the validity of the results were made.Thanks Jagir

Thanks for the efforts. Are you able to view the .xdmf file generated by the code? I can only see a line in the view.

**Comment by allanleal** [comment]
@Jagirhussan @Warmblood-b Let's chat on [gitter](https://gitter.im/reaktoro/community). I think it makes more sense to have another project where this demo with FEniCS is available. This is because FEniCS creates a dependency that may be difficult for some to address; so we do not impose this dependency on all users of Reaktoro. 

https://gitter.im/reaktoro/community

**Comment by Jagirhussan** [comment]
Hi Allan and Warmblood-b
    I was interested in the api’s and the manner in which FEM was being coupled. That example gave me a good idea of that and I have used it as a reference. I am using OpenFOAM and OpenCMISS for my work, so I have not invested effort into the validation of FEniCS outputs etc.. I also removed the VM that had the example and FEniCS so I not able to answer your query regarding the .xdmf file, from memory I also saw a line but since it was a effectively a 1D problem I did not read too much into it.

Regards
Jagir

**Comment by allanleal** [comment]
Hi @Jagirhussan, thanks for this PR. It's been forever to get action from my side on it, but Reaktoro no longer (for the past many years) has FEniCS code inside it, and this PR is therefore no longer applicable. I will close it, but check its contents in the future when we resume work on FEniCS + the new version 2 of Reaktoro (https://reaktoro.org).

**Pull request closed without merging**
